Accesibility
simplegoose/portfolio-project pull request #8
Opened 2022-12-13 20:01 UTC by astroboyReloaded

- Check for the page's title. No issues found.
- Add `alt` text to all `img` tags. 
- Check for headings outline. No issues found.
- Check for contrast colors: main text vs. background: contrast ratio: 9.64:1; form: ratio: 3.86:1.
- Resize text. No issues found.
- Check for keyboard access and visual focus. No issues found.

2022-12-13 20:24 UTC, mckent05 requested changes
Hi @astroboyReloaded, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Good job including a report in your PR 👏 
- Your PR is professional 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 20:24 UTC, mckent05 commented on index.html
> +                  ><img src="./assets/images/vectors/chill.svg" alt=""
- I can see that you have images with some missing `alt text` here. Please ensure that all images have an `alt` text. Remember to include the links to the changes you have made in the PR report 👍 👍

2022-12-13 20:24 UTC, mckent05 commented on index.html
> +                    <span>HTML</span>
- Please ensure all images have `alt text`, and remember to include the link to the changes you have made in your report 🙏

2022-12-13 20:24 UTC, mckent05 commented on index.html
> +                    ><img src="./assets/images/vectors/chill.svg" alt=""
- Please ensure all images have alt text, and remember to include the link to the changes you have made in your report 🙏

2022-12-14 16:27 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi Team! @astroboyReloaded @simplegoose, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 16:27 UTC, anagudelogu commented on index.html
> +                      <img src="./assets/images/vectors/html.png" alt="Image containing HTML icon" />
- [x] **[OPTIONAL]:** You did a great job working on the alternative text for your images! 🚀 However, I suggest that you do not include the "Image of" prefix on it. This is because since you're using an `<img>` tag, screen readers automatically provide that information. 🤓 🛠️

2022-12-14 16:27 UTC, anagudelogu commented on index.html
> +            </form>
- [x] **[OPTIONAL]:** In order to improve the accessibility of your page, I suggest that you modify the labels of the required fields of your contact form as explained below.

Following the [Easy Checks](https://www.w3.org/WAI/test-evaluate/preliminary/#forms) accessibility instructions for forms:

![image](https://user-images.githubusercontent.com/77069011/207383718-17a0b676-3bf8-43c4-ac44-2f2852e26514.png)

Please add an indicator of which fields are required (By convention, you could add an asterisk `*` to the label/placeholder text to indicate that it is required)! 🤓 🛠️

2022-12-15 09:12 UTC, merged